API/urls.py
from django.urls import path
from . import views

app_name = 'API'

urlpatterns = [
    path('category/list', views.CategoryList.as_view(), name='API-category-list'),
    path('tag/list', views.TagList.as_view(), name='APi-tags-list'),
    path('survey/list/<int:c_id>', views.SurveyList.as_view(), name='API-survey-list'),
    path('survey/list/<int:c_id>/filtered-by/<int:tag>', views.TagFilteredSurveyList.as_view(), name='API-survey-list'),
    path('survey/list/<int:c_id>/sorted-by/<str:key>/order/<int:order>', views.FieldSortedSurveyList.as_view(), name='API-survey-list'),
    path('survey/list/<int:c_id>/search/', views.InputFilteredSurveyList.as_view(), name='API-survey-list'),
    path('survey/create', views.CreateSurvey.as_view(), name='API-survey-create'),
    path('survey/<int:pk>/stats/<str:q>/<str:c>/<str:cs>/<str:ed>/<str:ws>/<str:gen>/<str:country>/<str:city>',
         views.SurveyStats.as_view(), name='API-survey-stats'),
    path('profile/search/<str:username>', views.ProfileGet.as_view(), name='API-profile-create'),
    path('profile/create', views.ProfileCreate.as_view(), name='API-profile-create'),
    path('profile/my', views.MyProfile.as_view(), name='API-profile'),
    path('survey/list/my', views.MySurveyList.as_view(), name='API-survey-my'),
    path('survey/list/my/filtered-by/<int:tag>', views.MyTagFilteredSurveyList.as_view(), name='API-survey-list'),
    path('survey/list/my/sorted-by/<str:key>/order/<int:order>', views.MyFieldSortedSurveyList.as_view(),
         name='API-survey-list'),
    path('survey/list/my/search/', views.MyInputFilteredSurveyList.as_view(), name='API-survey-list'),
    path('submission/list/my', views.MySubmissionList.as_view(), name='API-submission-my'),
    path('survey/<int:pk>/my', views.MySubmissionDetail.as_view(), name='API-submission-my'),
    path('survey/detail/<int:pk>/creator', views.DetailedSurveyCreator.as_view(), name='API-survey-creator-detail'),
    path('survey/detail/<int:pk>/submitter', views.DetailedSurveySubmitter.as_view(), name='API-survey-submitter-detail'),
    path('survey/<int:pk>/edit', views.EditSurvey.as_view(), name='API-survey-edit'),
    path('survey/<int:pk>/question/create', views.CreateQuestion.as_view(), name='API-question-create'),
    path('survey/<int:pk>/question/<int:id>/edit', views.EditQuestion.as_view(), name='API-question-edit'),
    path('survey/<int:pk>/question/<int:id>/choice/create', views.CreateChoice.as_view(), name='API-choice-create'),
    path('survey/<int:pk>/question/<int:id>/choice/<int:c_id>/edit', views.EditChoice.as_view(), name='API-choice-edit'),
    path('survey/<int:pk>/question/<int:id>/choice-list', views.QuestionChoiceList.as_view(), name='API-question-choice-list'),
    path('survey/<int:pk>/submission-start', views.SubmissionCreate.as_view(), name='API-submission-new'),
    path('submission/<int:pk>/answers-create', views.AnswersCreate.as_view(), name='API-submission-answers-new'),
]

SurveyApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('polls.urls', namespace='polls')),
    path('api/', include('API.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
    path('api/rest-auth/registration/', include('rest_auth.registration.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from .views import HomeView, survey_list, CreateSurveyView, edit, question_create, choice_create, detail, start, \
    submit, thanks, EditProfileView, filter_surveys_by_input, filter_surveys_by_tag, ProfileView, view_submission, \
    add_other, survey_detail_stats, load_choices, delete_stop, survey_delete, survey_stop, my_surveys, my_submissions, \
    choice_delete, choice_edit, question_delete, question_edit, survey_info_edit

app_name = 'polls'

urlpatterns = [
    path("", HomeView.as_view(), name='home'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/my-surveys', my_surveys, name='my-surveys'),
    path('profile/my-submissions', my_submissions, name='my-submissions'),
    path('profile-edit/', EditProfileView.as_view(), name='profile-edit'),
    path('survey-list/<slug>', survey_list, name='survey-list'),
    path('survey-list/<slug>/search/', filter_surveys_by_input, name='survey-filter-input'),
    path('survey-list/<slug>/tag=<tag>/', filter_surveys_by_tag, name='survey-filter-tag'),
    path('surveys/create/', CreateSurveyView.as_view(), name='survey-create'),
    path('surveys/<int:pk>/edit', edit, name='survey-edit'),
    path('surveys/<int:pk>/edit-info', survey_info_edit, name='survey-edit-info'),
    path('surveys/<int:pk>/delete-stop', delete_stop, name='survey-delete-stop'),
    path('surveys/<int:pk>/delete', survey_delete, name='survey-delete'),
    path("surveys/<int:pk>/delete", survey_delete, name='survey-delete'),
    path("surveys/<int:pk>/stop", survey_stop, name='survey-stop'),
    path("surveys/<int:pk>/", detail, name="survey-detail"),
    path("surveys/<int:pk>/question/", question_create, name="question-create"),
    path("surveys/<int:pk>/question/<int:question_pk>/delete", question_delete, name="question-delete"),
    path("surveys/<int:pk>/question/<int:question_pk>/edit", question_edit, name="question-edit"),
    path("surveys/<int:survey_pk>/question/<int:question_pk>/choice/", choice_create, name="choice-create"),
    path("surveys/<int:survey_pk>/question/<int:question_pk>/add-other/", add_other, name='survey-edit-other'),
    path("surveys/<int:survey_pk>/question/<int:question_pk>/choice/<int:choice_pk>/delete", choice_delete,
         name="choice-delete"),
    path("surveys/<int:survey_pk>/question/<int:question_pk>/choice/<int:choice_pk>/edit", choice_edit,
         name="choice-edit"),
    path("surveys/<int:pk>/start/", start, name="survey-start"),
    path("surveys/<int:survey_pk>/submit/<int:sub_pk>/", submit, name="survey-submit"),
    path("surveys/<int:survey_pk>/view-submission/<int:sub_pk>/", view_submission, name="submission-view"),
    path("surveys/<int:pk>/thanks/", thanks, name="survey-thanks"),
    path("surveys/<int:pk>/stats/#<str:sf>", survey_detail_stats, name="survey-stats"),
    path('ajax/load-choices/<int:pk>', load_choices, name='ajax_load_choices'), # AJAX

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/choice_filter.html
{% include "base.html" %}
<option value="0">Non Selezionato</option>
{% for choice in choices %}
    <option value="{{ choice.pk }}">{{ choice.text }}</option>
{% endfor %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://bitbucket.org/giakog/surveyapp/src/master/" target="_blank">
        <i class="fab fa-bitbucket mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <div class="footer-copyright py-3">
      © 2021 Giacomo Gilioli
    </div>

  </footer>

templates/home.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">
        <h1 class="ui header text-center">
            Selezione Categoria Sondaggi
        </h1>

      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for cat in category_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                <img src="media/{{ cat.image }}" class="card-img-top">
                <a href="{{ cat.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <h5>
                  <strong>
                      {%  if cat.title == "All" %}
                        <a href="{{ cat.get_absolute_url }}" class="dark-grey-text">Tutte</a>
                      {% else %}
                        <a href="{{ cat.get_absolute_url }}" class="dark-grey-text">{{ cat.title }}</a>
                        {% endif %}
                  </strong>
                </h5>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Precedente</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(Corrente)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Prossima</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

templates/my_submissions.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h2>Mie Sottomissioni</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Sondaggio</th>
                        <th>Creato il</th>
                        <th>Stato</th>
                        <th>Azioni</th>
                    </tr>
                </thead>
                <tbody>
                    {% for submission in submissions %}
                    <tr>
                        <td>
                            <b>{{ submission.survey.title }}</b>
                        </td>
                        <td>{{ submission.created_at }}</td>
                        <td>
                            {% if submission.is_complete %}
                                <b class="green-text" >Completo</b>
                            {% else %}
                                <b>Iniziato</b>
                            {% endif %}
                        </td>
                        <td>
                        {% if submission.is_complete %}
                            <a href="{% url 'polls:submission-view' submission.survey.id submission.id %}">
                                 <div class="ui button">vedi</div>
                            </a>
                        {% else %}
                            <a href="{% url 'polls:survey-submit'  submission.survey.id submission.id %}">
                             <div class="ui button">continua</div>
                            </a>
                        {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Non hai effettuato nessuna sottomissione</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
  </main>
{% endblock content %}

templates/my_surveys.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>Miei Sondaggi</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Categoria</th>
                        <th>Creato il</th>
                        <th>Stato</th>
                        <th>Sottomissioni</th>
                        <th>Azioni</th>
                    </tr>
                </thead>
                <tbody>
                {% for survey in surveys%}
                    <tr>
                        <td>{{ survey.title }}</td>
                        <td>{{ survey.category }}</td>
                        <td>{{ survey.date }}</td>
                        <td>
                            {% if survey.status == '1' %}
                                <b class="green-text">Attivo</b>
                            {% elif survey.status == '2' %}
                                <b class="orange-text">Bloccato</b>
                            {% else %}
                                <b class="red-text">Inattivo</b>
                            {% endif %}
                        </td>
                        <td>{{ survey.count }}</td>
                        <td>
                            {% if survey.status == '1' or survey.status == '2'%}
                                <a href="{% url 'polls:survey-detail' survey.pk %}">
                                     <div class="ui button">vedi</div>
                                </a>
                                <a href="{% url 'polls:survey-delete-stop' pk=survey.pk %}">
                                     <div class="ui button">blocca/cancella</div>
                                </a>
                            {% elif survey.status == '0' %}
                                <a href="{% url 'polls:survey-edit' survey.pk %}">modifica</a>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                <tr>
                    <td colspan='5'>Non hai creato nessun sondaggio</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
  </main>

{% endblock content %}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">SurveyBeacon</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'polls:survey-create' %}">
              <span class="clearfix d-none d-sm-inline-block"> Crea Sondaggio </span>
            </a>
          </li>
              <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'polls:profile' %}">
              <span class="clearfix d-none d-sm-inline-block"> {{ user.username }} </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Registrati </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/new_survey.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Create - Surveys{% endblock %}
{% block content %}
<div class="container wow fadeIn">
    <main>
        <h2 class="my-5 h2 text-center">
            Crea Nuovo Sondaggio
        </h2>
            <div class="row">
                <form method="POST" class="card-body {% if form.errors %} error {% endif %}" novalidate>
                    {% csrf_token %}
                    <h3>Informazioni Sondaggio</h3>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="field">
                        <label>{{ field.label_tag }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <strong class="red">{{ error }}</strong>
                        {% endfor %}

                    {% endfor %}
                    </div>
                    <button type="submit" class="btn-primary btn">Crea</button>
                </form>
            </div>
    </main>
</div>
{% endblock %}

templates/profile_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Edit - Profile{% endblock %}
{% block content %}
<div class="container wow fadeIn">
    <main>
        <h2 class="my-5 h2 text-center">
            Modifica Profilo
        </h2>
            <div class="row">
                <form method="POST" class="card-body {% if form.errors %} error {% endif %}" novalidate>
                    {% csrf_token %}
                    <h3>Profile Info</h3>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="field">
                        <label>{{ field.label_tag }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <strong class="red">{{ error }}</strong>
                        {% endfor %}
                    {% endfor %}
                    </div>
                    <button type="submit" class="btn-primary btn">Conferma</button>
                </form>
            </div>
    </main>
</div>
{% endblock %}

templates/question.html
{% extends "base.html" %}
{% block title %}Question - Surveys{% endblock %}

{% block content %}
    <div class="container emp-profile">
    <main>
        <div class="row">
            <div class="col-md-6">
                <div class="profile-head">
                    <h1 class="ui header">Crea Nuova Domanda</h1>
                        <div class="ui basic padded segment left aligned">
                            <form class="ui form {% if form.errors %}error{% endif %}" method="post" novalidate>
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="field {% if field.errors %}error{% endif %}">
                                    <label>{{ field.label_tag }}</label>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="ui btn-primary btn">Crea Domanda</button>
                            <a href="{% url 'polls:survey-edit' survey.pk %}">
                                <div class="ui button">Cancella</div>
                            </a>
                            <div class="ui message error">
                                {% if field.errors %}
                                    <div class="header">Ci sono dei problemi</div>
                                {% endif %}
                                <ul class="list">
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <li>{{ field.label_tag }} {{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </form>
                        </div>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

templates/submit.html
{% extends "base.html" %}
{% block title %}Submit - Surveys{% endblock %}

{% block content %}
<style>
    form .field ul {
        list-style: none;
        padding: 0 1rem;
    }

    form .field li {
        margin-bottom: 0.3rem;
    }
</style>
<div class="container emp-profile">
    <div class="row">
        <div class="col-md-6">
            <div class="profile-head">
            <h1 class="ui header dividing">Tue Risposte a {{ survey.title }}</h1>
            <form method="post" novalidate>
                {% csrf_token %}
                {{ formset.management_form }}
                {{ other_formset.management_form }}
                {% for question, form, o_form in question_forms %}
                <div class="ui basic padded segment left aligned">
                    <div class="ui form {% if form.errors %}error{% endif %}">
                        <h4 class="ui header">
                            {{ forloop.counter }}): {{ question.text }}
                        </h4>
                        {% for field in form %}
                            <div class="field{% if field.errors %}error{% endif %}">
                                {{ field }}
                            </div>
                        {% endfor %}
                            {% for f in o_form %}
                                {% if question.other_field == True %}
                                    <div class="field{% if f.errors %}error{% endif %}">
                                        {{ f }}
                                    </div>
                                {% endif %}
                            {% endfor %}

                        <div class="ui message error">
                            {% if field.errors %}
                                <div class="header">Ci sono dei problemi</div>
                                <ul class="list">
                                    {% for field in form %}
                                    {% for error in field.errors %}
                                    <li>{{ field.label_tag }} {{ error }}</li>
                                    {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
                <button type="submit" name="send" class="ui btn-primary btn" value="1">Conferma</button>
                {% comment %}<button type="submit" name="send" class="ui primary button" value="2">Save</button>{% endcomment %}
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/survey_edit.html
{% extends "base.html" %}
{% block title %}Create - Surveys{% endblock %}

{% block content %}
<div class="container emp-profile">
    <main>
    <div class="row">
        <div class="col-md-6">
            <div class="profile-head">
                <h1 class="ui header">Aggiungi Domande a {{survey.title}}</h1>
                <div class="ui container left aligned">
                    <a href="{% url 'polls:survey-edit-info' survey.id %}"
                       class="ui-button">[modifica]</a>
                    <a href="{% url 'polls:survey-delete' survey.id %}"
                       class="ui-button">[elimina]</a>
                    {% for question in questions %}
                        <div class="ui basic padded segment">
                            <h4 class="ui header">
                                Domanda {{ forloop.counter }} / {{ questions|length }}: {{ question.text }}
                                <a href="{% url 'polls:question-edit' survey.id question.id %}"
                                   class="ui-button">[modifica]</a>
                                <a href="{% url 'polls:question-delete' survey.id question.id %}"
                                   class="ui-button">[elimina]</a>
                            </h4>
                            <ul>
                                {% for option in question.choices.all %}
                                    {% if question.type == "0" %}
                                        <li>
                                            {{ forloop.counter }}) {{option.text}}
                                            <a href="{% url 'polls:choice-edit' survey.id question.id option.id %}"
                                                class="ui-button">[modifica]</a>
                                            <a href="{% url 'polls:choice-delete' survey.id question.id option.id%}"
                                                class="ui-button">[elimina]</a>
                                        </li>
                                    {% endif %}
                                    {% if question.type == "1" %}
                                        {{ option.text }}
                                        {% if forloop.counter == question.choices.all|length %}
                                            <a href="{% url 'polls:choice-create' survey.id question.id %}"
                                                class="ui-button">[modifica]</a>
                                            <a href="{% url 'polls:choice-delete' survey.id question.id option.id %}"
                                               class="ui-button">[elimina]</a>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                    {% if question|length < 20 %}
                        <a href="{% url 'polls:question-create' survey.pk %}">
                            <div class="ui button">Aggiungi Domanda</div>
                        </a>
                    {% endif %}
                    {% if questions|length > 0 %}
                        <div class="ui divider"></div>
                        <form style="display: inline-block;" method="post">
                            {% csrf_token %}
                            <button type="submit" name="send" value="1" class="btn-primary btn"
                                onclick="return confirm('Attivare il sondaggio?');">Attiva Sondaggio</button>
                            <button type="submit" name="send" value="2" class="btn-danger btn"
                                onclick="return confirm('Sei sicuro?');">Elimina Sondaggio</button>
                        </form>
                        <a href="{% url 'polls:profile' %}">
                            <div class="ui button">Indietro</div>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </main>
</div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block title %}Thanks - Surveys{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6" style="float: none; margin: 0 auto;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="text-align: center;">
                        {% if survey.thanks_message == "" %}
                            <h1 class="ui header"> Survey completata, grazie del vostro tempo.</h1>
                        {% else %}
                            <h1 class="ui header">{{ survey.thanks_message }}</h1>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}